### ISSUE TITLE
Epic: create config snapshot collector

### ISSUE THREAD

**Issue by turnrye** [memhamwan/infrastructure-configuration#7]
Router configs change routinely and we dont have an audit log. We could pretty easily scrape all devices configs every day and save them as files using ansible. Then commit that to a repo. This could be done entirely using automation as a k8s cronjob.

**Comment by turnrye** [comment]
Where this stands:

- If you clone the https://github.com/memhamwan/routeros-config-audit repo along side this one, you can manually run the audit
- `ansible-playbook --vault-password-file .vault-password -i memphis.yml dump-routeros.yml` kicks it off and failed hosts are ignored
- You then manually have to commit the results (and Ive noticed that sometimes, log messages get mixed in with the exports... seems like an area for improvement)

So still todo:
- [ ] Automate all of these steps in a cron
- [ ] Make it actually do something with the report, like perhaps push to prometheus with the number of missed hosts or something
- [ ] Update teh ansible script to disable all echo logs before running the export, then enable them again (though maybe we should just delete this log config altogether?)
